### ISSUE TITLE
ActivityNotFoundException: No Activity found to handle Intent (Youtube Video)

### ISSUE THREAD

**Issue by jorgegil96** [jorgegil96/All-NBA#225]
```
Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=vnd.youtube:K-8_ZcAnuSI launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1839)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
       at android.app.Activity.startActivityForResult(Activity.java:4389)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
       at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
       at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:932)
       at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
       at android.support.v4.app.Fragment.startActivity(Fragment.java:940)
       at android.support.v4.app.Fragment.startActivity(Fragment.java:929)
       at com.gmail.jorgegilcavazos.ballislife.features.highlights.home.HighlightsFragment.openYoutubeVideo(HighlightsFragment.java:307)
       at com.gmail.jorgegilcavazos.ballislife.features.highlights.home.HighlightsPresenter$2.onNext(HighlightsPresenter.java:160)
       at com.gmail.jorgegilcavazos.ballislife.features.highlights.home.HighlightsPresenter$2.onNext(HighlightsPresenter.java:144)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by paynemiller92** [comment]
@jorgegil96 Any steps to reproduce? I will be happy to take a look!

**Comment by jorgegil96** [comment]
I haven't been able to reproduce it, but I suspect it might be cause by clients that don't have the youtube app/play services installed. You could check the youtube API docs of the player I'm using, there's probably a method for checking compatibility before launching the intent that I didn't implement.
